[package]
name = "reaper-region-reader"
version = "0.1.0"
description = "Parse Reaper region markers from WAV files"
edition = "2024"

[workspace]
members = ["wavtag"]

[dependencies]
clap = { version = "4", features = ["derive"] }
csv = "1"
env_logger = "0.11"
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

# wavtag: https://github.com/monomadic/zodak.git
wavtag = { path = "wavtag" }
