[package]
name = "reaper-region-reader"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11"
log = "0.4"
wavtag = { git = "https://github.com/monomadic/zodak.git", package = "wavtag" }
